### ISSUE TITLE
CNAME file is deleted on deploy

### ISSUE THREAD

**Issue by s0ph1e** [DavidS/jekyll-deploy#4]
Hey @DavidS  👋 

Thank you for this action! 

I've noticed that CNAME file which is used to deploy jekyll site to custom domain is removed after commit to `gh-pages` branch (caused by `git reset --soft origin/gh-pages`). It would be nice to copy it from master branch on build. 

I've fixed that by adding this line to entrypoint
```ruby
FileUtils.cp('../CNAME', 'CNAME')
```

**Comment by DavidS** [comment]
Hey @s0ph1e! 

Thanks for writing in. In my limited testing, jekyll deployed the CNAME file automatically into the _site directory:

```
$ jekyll new _test
Running bundle install in /home/david/.../_test... 
[...]
New jekyll site installed in /home/david/.../_test. 
$ cd _test/
$ echo test.example.com > CNAME
$ ls
404.html  about.markdown  CNAME  _config.yml  Gemfile  index.markdown  _posts
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.7
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.13.1
Using forwardable-extended 2.6.0
Using i18n 1.8.5
Using sassc 2.4.0
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Using listen 3.2.1
Using jekyll-watch 2.2.1
Using rexml 3.2.4
Using kramdown 2.3.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.22.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using jekyll 4.0.1
Using jekyll-feed 0.15.0
Using jekyll-seo-tag 2.6.1
Using minima 2.5.1
Bundle complete! 6 Gemfile dependencies, 31 gems now installed.
Bundled gems are installed into `/home/david/gems/`
$ bundle exec jekyll build --strict --trace --baseurl=$(pwd)/_site --future
Configuration file: /home/david/.../_test/_config.yml
            Source: /home/david/.../_test
       Destination: /home/david/.../_test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.341 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
$ find _site/
_site/
_site/404.html
_site/about
_site/about/index.html
_site/index.html
_site/assets
_site/assets/main.css
_site/assets/main.css.map
_site/assets/minima-social-icons.svg
_site/feed.xml
_site/CNAME
_site/jekyll
_site/jekyll/update
_site/jekyll/update/2020
_site/jekyll/update/2020/08
_site/jekyll/update/2020/08/26
_site/jekyll/update/2020/08/26/welcome-to-jekyll.html
$
```

Please provide more details how this is going wrong for you. Maybe we can figure it out.

**Comment by aivus** [comment]
Hey @DavidS 

To reproduce this issue you need to use your GH action (jekyll-deploy) for the repository.
The problem caused by this git operation: https://github.com/DavidS/jekyll-deploy/blob/c5ae968495d8474408d4fab84281562961cace43/entrypoint.rb#L33

It executes `git reset --soft origin/gh-pages` which is removing CNAME file from the `gh-pages` branch.

I've made some PoC to show this:
1. Look here: https://github.com/aivus/personal-website/tree/gh-pages
This branch contains `CNAME` file which should be used by Github.

2. When I'm making changes to the main branch (`davids-jekyll-issue` in my case) `jekyll-deploy` action builds pages and executes `git reset --soft ...` command which removes original CNAME file from `gh-pages` branch, because this file doesn't exist in `_site`.
See https://github.com/aivus/personal-website/runs/1031424064?check_suite_focus=true#step:5:290

**Comment by DavidS** [comment]
Ah, browsing through the log, I see you're using jekyll 3, while I've been testing with jekyll 4. The latter seems to copy all plain files over by default, which is why I didn't see the behaviour.

**Comment by DavidS** [comment]
Please let me know if the change in https://github.com/DavidS/jekyll-deploy/pull/14 works for you.

**Comment by aivus** [comment]
`CNAME` works fine now. Thanks. 👍
